// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_mcmc_opt
Rcpp::List run_mcmc_opt(int iterations, int burn, int L, const Rcpp::List& As, const arma::vec& Y, const arma::mat& X, const Rcpp::List& inits, const Rcpp::IntegerVector& landmark_idx_R);
RcppExport SEXP _BPSMKL_run_mcmc_opt(SEXP iterationsSEXP, SEXP burnSEXP, SEXP LSEXP, SEXP AsSEXP, SEXP YSEXP, SEXP XSEXP, SEXP initsSEXP, SEXP landmark_idx_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type As(AsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type landmark_idx_R(landmark_idx_RSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc_opt(iterations, burn, L, As, Y, X, inits, landmark_idx_R));
    return rcpp_result_gen;
END_RCPP
}
// get_K_cpp
arma::mat get_K_cpp(int update, const arma::mat& X, const arma::mat& Eta, const arma::vec& lambda, const Rcpp::IntegerMatrix& idx, int eta, int i, int j);
RcppExport SEXP _BPSMKL_get_K_cpp(SEXP updateSEXP, SEXP XSEXP, SEXP EtaSEXP, SEXP lambdaSEXP, SEXP idxSEXP, SEXP etaSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type update(updateSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(get_K_cpp(update, X, Eta, lambda, idx, eta, i, j));
    return rcpp_result_gen;
END_RCPP
}
// extract_edges_fast
IntegerMatrix extract_edges_fast(const arma::mat& A);
RcppExport SEXP _BPSMKL_extract_edges_fast(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(extract_edges_fast(A));
    return rcpp_result_gen;
END_RCPP
}
// run_mcmc
Rcpp::List run_mcmc(int iterations, int burn, int L, const Rcpp::List& As, const arma::vec& Y, const arma::mat& X, const Rcpp::List& inits);
RcppExport SEXP _BPSMKL_run_mcmc(SEXP iterationsSEXP, SEXP burnSEXP, SEXP LSEXP, SEXP AsSEXP, SEXP YSEXP, SEXP XSEXP, SEXP initsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type As(AsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inits(initsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc(iterations, burn, L, As, Y, X, inits));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BPSMKL_run_mcmc_opt", (DL_FUNC) &_BPSMKL_run_mcmc_opt, 8},
    {"_BPSMKL_get_K_cpp", (DL_FUNC) &_BPSMKL_get_K_cpp, 8},
    {"_BPSMKL_extract_edges_fast", (DL_FUNC) &_BPSMKL_extract_edges_fast, 1},
    {"_BPSMKL_run_mcmc", (DL_FUNC) &_BPSMKL_run_mcmc, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BPSMKL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
