# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_opt <- function(iterations, burn, L, As, Y, X, inits, landmark_idx_R) {
    .Call(`_BPSMKL_run_mcmc_opt`, iterations, burn, L, As, Y, X, inits, landmark_idx_R)
}

get_K_cpp <- function(update, X, Eta, lambda, idx, eta = -1L, i = -1L, j = -1L) {
    .Call(`_BPSMKL_get_K_cpp`, update, X, Eta, lambda, idx, eta, i, j)
}

extract_edges_fast <- function(A) {
    .Call(`_BPSMKL_extract_edges_fast`, A)
}

run_mcmc <- function(iterations, burn, L, As, Y, X, inits) {
    .Call(`_BPSMKL_run_mcmc`, iterations, burn, L, As, Y, X, inits)
}

